
title: Recipes
author: Nick Willems

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  hide_site_feed_link: true
  nav_pages:
    - index.html
layouts_dir: _layouts

# files and folders
exclude:
  - generate_index.sh
  - .github/
