
title: Recipes
author: 
  name: Nick Willems

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
just_the_docs:
  color_scheme: dark

layouts_dir: _layouts

# files and folders
exclude:
  - generate_index.sh
  - .github/
