
title: Recipe Collection
url: "https://nwillems94.github.io" 
baseurl: "/recipes"

# Build settings
markdown: kramdown
theme: 
  minima:
  skin: dark
permalink: pretty
layouts_dir: _layouts

# files and folders
include:
  - index.html
  - recipes/*
