
title: Recipes
author: 
  name: Nick Willems

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: dark

layouts_dir: _layouts

# files and folders
exclude:
  - generate_index.sh
  - .github/

collections:
  breads:
    output: true
  breakfast:
    output: true
  desserts:
    output: true
  dinners:
    output: true
  cocktails:
    output: true
  sauces: 
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
    breads:
      name: Breads
    breakfast:
      name: Breakfast
    desserts:
      name: Desserts
    dinners:
      name: Dinners
    cocktails:
      name: Cocktails
    sauces:
      name: Sauces