
title: Recipe Collection
description: A collection of delicious recipes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: 
  minima:
  skin: dark
permalink: pretty
layouts_dir: _layouts

# Source and destination folders
source: recipes
destination: docs

# Exclude files and folders
exclude:
  - generate_index.sh
  - .github
