name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  jekyll-build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Jekyll and Bundler
      run: |
        gem install bundler jekyll

    - name: Build site with Jekyll
      run: |
        mkdir -p docs
        jekyll build --source recipes --destination docs

    - name: Commit built site
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git pull
        git add docs
        git commit -m "Build Jekyll site from recipes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}